import Link from "next/link";
import { SiteEffects } from "./site-effects";
import { SiteNavigation } from "./site-navigation";

export function JsonLd({data}:{data:object}) { return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}} /> }
export function MetaLine(){return <div className="meta-line"><span>Редакция Rudollforum</span><span>Опубликовано: 24 июля 2026</span><span>Обновлено: 24 июля 2026</span></div>}
export function SiteShell({children}:{children:React.ReactNode}) {
  return <><SiteEffects/><header className="site-header"><div className="topline">18+ · Информационный ресурс для совершеннолетней аудитории</div><div className="header-inner"><Link href="/" className="brand"><i className="lotus" aria-hidden="true">✦</i><span className="brand-title"><strong>Rudollforum</strong><em className="header-age">18+</em></span><span className="brand-subtitle">TPE и силиконовые куклы</span><small>Независимый справочник по выбору, покупке, уходу и хранению</small></Link><SiteNavigation/></div></header><main>{children}</main><footer><div className="footer-ornament" aria-hidden="true">✦　◇　✦</div><div className="footer-grid"><div><div className="footer-brand"><span className="footer-lotus">✦</span> Rudollforum</div><p>Независимый справочник по выбору, покупке, уходу и хранению силиконовых и ТПЕ-кукол.</p><span className="age-mark">18+ · Информационный ресурс</span><p className="footer-disclaimer">Rudollforum является независимым информационным справочником и сообществом владельцев силиконовых и ТПЕ-кукол. Сайт не принимает оплату и не оформляет заказы.</p></div><div><strong>Основное</strong><Link href="/guide">Практическое руководство</Link><a href="/documents/rudollforum-guide-tpe-silicone-2026.pdf" target="_blank" rel="noopener noreferrer">Руководство PDF ↗</a><Link href="/getting-started">С чего начать</Link><Link href="/safe-purchase">Безопасная покупка</Link><Link href="/shops/moon-doll-guide">Заказ на Moon-Doll</Link></div><div><strong>Эксплуатация</strong><Link href="/care">Уход</Link><Link href="/storage">Хранение</Link><Link href="/repair">Ремонт</Link></div><div><strong>О проекте</strong><Link href="/community">О сообществе</Link><Link href="/editorial-policy">Редакционная политика</Link><Link href="/age-policy">Возрастные ограничения</Link><Link href="/useful-links">Полезные ссылки</Link><a href="https://t.me/rudollforum" target="_blank" rel="noopener noreferrer">Telegram ↗</a><a href="https://www.moon-doll.com/" target="_blank" rel="noopener noreferrer sponsored">Moon-Doll ↗</a></div></div><div className="copyright"><span>18+. Сайт предназначен только для совершеннолетней аудитории.</span><span>© 2026 Rudollforum · Сайт не продаёт товары и не принимает оплату.</span></div></footer></>
}
